services:

  sender-q6:
    image: sender-q6
    build:
      context: .
      dockerfile: Dockerfile.sender
    container_name: sender-q6
    ports:
      - "10000:10000/udp"
    networks:
      - test-network
    depends_on:
      - router-1
    volumes:
      - ./metrics:/app/metrics

  router-1:
    image: router-1
    build:
      context: .
      dockerfile: Dockerfile.router1
    container_name: router-1
    ports:
      - "10001:10001/udp"
    networks:
      - test-network
    depends_on:
      - router-2

  router-2:
    image: router-2
    build:
      context: .
      dockerfile: Dockerfile.router2
    container_name: router-2
    ports:
      - "10002:10002/udp"
    networks:
      - test-network
    depends_on:
      - router-3

  router-3:
    image: router-3
    build:
      context: .
      dockerfile: Dockerfile.router3
    container_name: router-3
    ports:
      - "10003:10003/udp"
    networks:
      - test-network
    depends_on:
      - router-4

  router-4:
    image: router-4
    build:
      context: .
      dockerfile: Dockerfile.router4
    container_name: router-4
    ports:
      - "10004:10004/udp"
    networks:
      - test-network
    depends_on:
      - receiver-q6

  receiver-q6:
    image: receiver-q6
    build:
      context: .
      dockerfile: Dockerfile.receiver
    container_name: receiver-q6
    ports:
      - "10005:10005/udp"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
