services:

  sender-q6:
    image: sender-q6
    build:
      context: .
      dockerfile: Dockerfile.sender
    container_name: sender-q6
    ports:
      - "11000:10000"
    networks:
      - test-network

  router-1:
    image: router-1
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router-1
    ports:
      - "10001:10000"
    networks:
      - test-network

  router-2:
    image: router-2
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router-1
    ports:
      - "10001:10000"
    networks:
      - test-network

  router-3:
    image: router-1
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router-1
    ports:
      - "10001:10000"
    networks:
      - test-network

  router-4:
    image: router-1
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router-1
    ports:
      - "10001:10000"
    networks:
      - test-network



  receiver-q6:
    image: router-1
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router-1
    ports:
      - "10001:10000"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  db_volume: