start:
	@echo "Starting the project"
	@docker compose up -d --build --remove-orphans

run-server:
	@echo "Running server"
	@docker compose up -d server

run-sender:
	@echo "Running sender"
	@docker compose run sender