networks:
  subnet-A:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

  subnet-B:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/24


services:
  # Roteador/Firewall
  firewall:
    build:
      context: ./firewall
    container_name: firewall
    cap_add:
      - NET_ADMIN  # Permissões para manipular as configurações de rede
    sysctls:
      net.ipv4.ip_forward: "1"  # Habilitar roteamento de pacotes
    networks:
      subnet-A:
        ipv4_address: 10.0.0.5
      subnet-B:
        ipv4_address: 20.0.0.5

  # router:
  #   image: ubuntu:latest
  #   container_name: router
  #   networks:
  #     subnet-B:
  #       ipv4_address: 20.0.0.5
  #     subnet-A:
  #       ipv4_address: 10.0.0.5
  #   command: bash -c "apt-get update && apt-get install -y iproute2 && bash"


  # Rede A
  host1-net-a:
    build: 
      context: ./net-a/host1
    container_name: host1-net-a
    networks:
      subnet-A:
        ipv4_address: 10.0.0.2

  host2-net-a:
    build: 
      context: ./net-a/host2
    container_name: host2-net-a
    networks:
      subnet-A:
        ipv4_address: 10.0.0.3

  dns-a:
    build: 
      context: ./net-a/dns
    container_name: dns-a
    ports:
      - "30051:53"
      - "30051:53/udp"
    networks:
      subnet-A:
        ipv4_address: 10.0.0.20

  web-a:
    build: 
      context: ./net-a/web
    container_name: web-a
    networks:
      subnet-A:
        ipv4_address: 10.0.0.10

  # Computadores Subrede B
  host1-net-b:
    build: 
      context: ./net-b/host1
    container_name: host1-net-b
    networks:
      subnet-B:
        ipv4_address: 20.0.0.2


  host2-net-b:
    build: 
      context: ./net-b/host2
    container_name: host2-net-b
    networks:
      subnet-B:
        ipv4_address: 20.0.0.3

  web-b:
    build: 
      context: ./net-b/web
    container_name: web-b
    networks:
      subnet-B:
        ipv4_address: 20.0.0.10

  dns-b:
    build: 
      context: ./net-b/dns
    container_name: dns-b
    ports:
      - "30052:53"
      - "30052:53/udp"
    networks:
      subnet-B:
        ipv4_address: 20.0.0.20